### ISSUE TITLE
Create a method KL() to give a common interface

### ISSUE THREAD

**Issue by v-i-s-h** [Naereen/KullbackLeibler.jl#2]
The current implementation needs to call klXYZ for each of the distribution XYZ. It will be great if you can provide a common interface to call KL divergence and dispatch depending on the type of the argument you get.
Ex:
```
using Distributions
# Example
KL( X1::Distributions.Bernoulli, X2::Distributions.Bernoulli ) = klBern( X1.p, X2.p )
KL( X1::Distributions.Exponential, X2::Distributions.Exponential ) = klExp( X1.θ, X2.θ )
# Use case
X = Bernoulli(0.33)
Y = Bernoulli(0.42)
d1 = KL( X, Y ) # Calc KL divergence for Bernoullli R.V
X = Exponential( 0.33 )
Y = Exponential( 0.42 )
d2 = KL( X, Y) # Calc KL div for Exponential R.V

```
I think this way, the users don't have to remember all the klXYZ function.

**Comment by Naereen** [comment]
Hi!
It's smart, I'll try this when I have the time. Thanks for the suggestion!

**Comment by Naereen** [comment]
It should start to be OK. See [the doc](https://naereen.github.io/KullbackLeibler.jl/docs/index.html#KullbackLeibler.KL-Tuple{Any,Any})

It's what you suggested, right?

**Comment by v-i-s-h** [comment]
Exactly!! :) 

May be you should include this in the README page of git repo also. Or atleast a reference of this.

**Comment by Naereen** [comment]
OK. It is mentioned in the examples, second code block of examples, see https://github.com/Naereen/KullbackLeibler.jl#simple-usage

**Comment by v-i-s-h** [comment]
Great!!
Thanks for considering my suggestions. :)

**Comment by Naereen** [comment]
You're welcome! Thanks for suggesting it!

I read the Julia doc almost entirely, but you know how it is, when facing a real situation, you never think of the "unusual" things the language as to offer (here, overloading a function thanks to static typing).

**Comment by v-i-s-h** [comment]
Totally true.. :)
I'm following Julia almost two years now and every time I read the doc, I always learn a new way to code some stuff I did earlier.
